[package]
name = "simd-adler32"
authors = ["Marvin Countryman <me@maar.vin>"]
version = "0.1.0"
edition = "2018"
description = "SIMD accelerated Adler32 rolling hash."

[profile.release]
debug = true
opt-level = 2

[[bin]]
name = "profile"
path = "src/profile.rs"

[[bench]]
name = "adler32"
path = "bench/adler32.rs"
harness = false

[[bench]]
name = "compete"
path = "bench/compete.rs"
harness = false

[features]
default = ["std"]
std = []

[dependencies]
cfg-if = "1"

[dev-dependencies]
rand = "0.8"
criterion = "0.3"

# compition
adler = "1.0.2"
adler32 = "1.2.0"
