name: fuzz

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    working-directory: fuzz

jobs:
  fuzz:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        target: [avx2, sse2, ssse3]

    steps:
      - uses: actions/checkout@v2
      - name: setup
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - uses: Swatinem/rust-cache@v1
      - run: cargo install cargo-fuzz

      - name: cache corpus
        uses: actions/cache@v2
        with:
          path: fuzz/corpus
          key: ${{ matrix.target }}-${{ matrix.os }}

      - name: fuzz
        run: |
          cargo fuzz run ${{ matrix.target }} -- -max_total_time=900

      - name: archive artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: artifacts
          path: fuzz/artifacts
