name: fuzz

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    working-directory: fuzz

jobs:
  fuzz:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        target: [avx2, sse2, ssse3]

    steps:
      - uses: actions/checkout@v2
      - name: setup
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - run: cargo install cargo-fuzz

      - name: fuzz
        run: |
          cargo fuzz run ${{ matrix.target }}

      - name: archive report
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: fuzz/report
