name: fuzz

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

defaults:
  run:
    working-directory: fuzz

jobs:
  fuzz:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        target: [avx2, sse2, ssse3]

    steps:
      - uses: actions/checkout@v2
      - name: setup
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - run: cargo install afl

      - name: build
        run: |
          cargo afl build --bin ${{ matrix.target }} --release

      - name: fuzz
        run: |
          cargo afl fuzz -V 60 -i in -o report target/release/${{ matrix.target }}
        env:
          AFL_SKIP_CPUFREQ: 1
          AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES: 1

      - name: archive report
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: report
